language: bash

addons:
  apt:
    packages:
    - dia
    - inkscape
    - r-base-core
    - unoconv
    - libreoffice
    - poppler-utils
    - texlive-extra-utils

before_script:
  - pip install --user codecov && codecov

script:
    - make test
    - INSTALL_PATH=build make install
    - INSTALL_PATH=build make uninstall
