language: bash

addons:
    apt:
        packages:
        - dia
        - inkscape
        - r-base-core
        - unoconv
        - libreoffice
        - poppler-utils
        - texlive-extra-utils
        - lintian

#        # required by kcov
#        - elfutils
#        - libdw-dev
#        - libelf-dev
# after_success:
#   - bash <(curl -s https://codecov.io/bash)

script:
    - make                              # just show the message
    - make test                         # run tests
    - INSTALL_PATH=build make install   # try to install without sudo
    - INSTALL_PATH=build make uninstall # try to uninstall without sudo
    - make deb                          # build debian package and check with lintian
